# Generated by Django 3.0.8 on 2020-07-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200712_2353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Article',
        ),
    ]
