# Generated by Django 3.0.8 on 2020-07-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='build',
            field=models.CharField(default='Django', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(max_length=225),
        ),
    ]
